# Generated by Django 3.1.1 on 2021-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='username',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='prueba@example.com', max_length=254),
        ),
    ]
